<?php
require __DIR__ . '/../api/bootstrap.php';

$timestamp = date('Ymd-His');
$backupDir = __DIR__ . '/../backups';
if (!is_dir($backupDir) && !mkdir($backupDir, 0775, true) && !is_dir($backupDir)) {
  fwrite(STDERR, "FAIL: cannot create backups directory\n");
  exit(1);
}

$outputPath = $backupDir . "/db-backup-{$timestamp}.sql";
$pdo = get_pdo();
$tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);

$lines = [];
$lines[] = '-- Database backup generated by scripts/backup_db.php';
$lines[] = '-- Generated at: ' . gmdate('c');
$lines[] = 'SET FOREIGN_KEY_CHECKS=0;';
$lines[] = '';

foreach ($tables as $tableName) {
  $table = (string) $tableName;
  if ($table === '') {
    continue;
  }

  $escapedTable = str_replace('`', '``', $table);
  $createStmt = $pdo->query("SHOW CREATE TABLE `{$escapedTable}`")->fetch(PDO::FETCH_ASSOC);
  $createSql = (string) ($createStmt['Create Table'] ?? '');
  if ($createSql === '') {
    continue;
  }

  $lines[] = "-- Table: {$table}";
  $lines[] = "DROP TABLE IF EXISTS `{$escapedTable}`;";
  $lines[] = $createSql . ';';

  $rows = $pdo->query("SELECT * FROM `{$escapedTable}`")->fetchAll(PDO::FETCH_ASSOC);
  if (!empty($rows)) {
    $columns = array_keys($rows[0]);
    $columnSql = implode(', ', array_map(static function (string $column): string {
      return '`' . str_replace('`', '``', $column) . '`';
    }, $columns));

    foreach ($rows as $row) {
      $valueSql = [];
      foreach ($columns as $column) {
        $value = $row[$column];
        if ($value === null) {
          $valueSql[] = 'NULL';
        } else {
          $valueSql[] = $pdo->quote((string) $value);
        }
      }

      $lines[] = "INSERT INTO `{$escapedTable}` ({$columnSql}) VALUES (" . implode(', ', $valueSql) . ');';
    }
  }

  $lines[] = '';
}

$lines[] = 'SET FOREIGN_KEY_CHECKS=1;';
$lines[] = '';

file_put_contents($outputPath, implode(PHP_EOL, $lines));
echo $outputPath . PHP_EOL;
